name: Rust
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy 
          override: true
      - name: Install WinRT
        run: cargo install winrt
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: '-- --check --color always'
      - name: Fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch
      - name: Install WinRT Deps
        run: cargo winrt install
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: '--tests -- -D warnings'
  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v1
  build:
    name: Build
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Install WinRT
       run: cargo install winrt
     - name: Install WinRT Deps
       run: cargo winrt install
     - name: Build
       run: cargo build --verbose
     - name: Run Tests
       run: cargo test --all --verbose